### ISSUE TITLE
Missing wheels for python 3.12 for MacOS ARM

### ISSUE THREAD

**Issue by rafales** [mgd020/mjml-python#14]
**Describe the bug**
It seems that wheels for Python 3.12 for MacOS ARM are missing:

```
❯ poetry add mjml-python          
Using version ^1.2.1 for mjml-python

Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing mjml-python (1.2.1): Failed

  RuntimeError

  Unable to find installation candidates for mjml-python (1.2.1)

  at /opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│ 
       70│             links.append(link)
       71│ 
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│ 
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│ 

Cannot install mjml-python.
```

It works on Python 3.11.

Manually inspecting download files on PyPi (https://pypi.org/project/mjml-python/#files) shows that there are only two wheels for python 3.12 while there are four for python 3.11.

**To Reproduce**
1. Run `poetry add mjml-python` on MacOS M1/M2 and Python 3.12.

**Environment (please complete the following information):**
 - OS: MacOS 13.6
 - Arch: arm64
 - Python version: 3.12
 - Version: 1.2.1

**Additional context**

**Comment by rafales** [comment]
Can confirm that it works now. Thank you!

**Comment by blopker** [comment]
Hey! I also noticed that ARM builds for Linux are missing? This prevents me from running this in Docker on a Mac. From the code, I don't understand why it's not being made though.

**Comment by blopker** [comment]
Done! https://github.com/mgd020/mjml-python/issues/20
